# Generated by Django 3.2.9 on 2021-11-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('required', models.BooleanField(blank=True)),
                ('additional', models.BooleanField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('type_dishes', models.CharField(choices=[('Новинки', 'New'), ('Супы', 'Soups'), ('Салаты', 'Salads'), ('Пицца', 'Pizza'), ('Десерт', 'Dessert'), ('Напитки', 'Drinks')], default='Новинки', max_length=50)),
                ('img', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('ingredient', models.ManyToManyField(to='dishes.Ingredients')),
            ],
        ),
    ]
