# Generated by Django 3.2.9 on 2021-11-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dishes',
            options={'verbose_name_plural': 'Блюда'},
        ),
        migrations.AlterModelOptions(
            name='ingredients',
            options={'verbose_name_plural': 'Ингридиенты'},
        ),
        migrations.AddField(
            model_name='dishes',
            name='is_new',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='type_dishes',
            field=models.CharField(choices=[('Супы', 'Soups'), ('Салаты', 'Salads'), ('Пицца', 'Pizza'), ('Десерт', 'Dessert'), ('Напитки', 'Drinks')], default='Супы', max_length=50),
        ),
    ]
