# Generated by Django 3.2.9 on 2021-11-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0003_alter_dishes_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
