# Generated by Django 3.2.9 on 2021-11-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0004_alter_dishes_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='type_dishes',
            field=models.CharField(choices=[('Супы', 'Soups'), ('Салаты', 'Salads'), ('Пицца', 'Pizza'), ('Десерт', 'Dessert'), ('Напитки', 'Drinks')], default='Супы', max_length=50, null=True),
        ),
    ]
