# Generated by Django 3.2.9 on 2021-11-24 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0005_alter_dishes_type_dishes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=2, null=True)),
                ('type_dishes', models.CharField(choices=[('Супы', 'Soups'), ('Салаты', 'Salads'), ('Пицца', 'Pizza'), ('Десерт', 'Dessert'), ('Напитки', 'Drinks')], default='Супы', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='dishes',
            name='type_dishes',
        ),
        migrations.AddField(
            model_name='dishes',
            name='category_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dishes.categorydishes'),
        ),
    ]
